language: generic

sudo: required
services:
  - docker

before_install:
  - docker build-t alongal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alongal/docker-react -- --watchAll=false
