language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t alongal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alongal/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-765179075348"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
